<?php

namespace AppBundle\Repository;

/**
 * AgenciesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgenciesRepository extends \Doctrine\ORM\EntityRepository
{
}
