<?php

namespace AppBundle\Repository;

/**
 * DepartmentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepartmentsRepository extends \Doctrine\ORM\EntityRepository
{
}
