<?php

namespace AppBundle\Repository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends \Doctrine\ORM\EntityRepository {

    public function findAll() {
        return $this->findBy(array(), array('active' => 'DESC', 'date' => 'DESC'));
    }

}
