<?php

namespace AppBundle\Repository;

/**
 * SlidersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SlidersRepository extends \Doctrine\ORM\EntityRepository
{
}
