# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
#framework:
#        csrf_protection: ~

security:

    # https://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_WEBMARKETING: [ROLE_USER, ROLE_COMMERCIAL, ROLE_COMMUNICATION, ROLE_ALLOWED_TO_SWITCH]
        ROLE_COMMERCIAL: [ROLE_USER, ROLE_ALLOWED_TO_SWITCH]
        ROLE_COMMUNICATION: [ROLE_USER, ROLE_ALLOWED_TO_SWITCH]
        ROLE_ADMIN: [ROLE_COMMUNICATION, ROLE_COMMERCIAL, ROLE_USER, ROLE_WEBMARKETING, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        main:
            entity:
                class: AppBundle\Entity\User

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern : ^/
            anonymous: ~
            provider: main
            logout_on_user_change: true
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout:       true
            anonymous:    true
            remember_me:
                secret: '%secret%'
                lifetime: 604800
                path: /

    access_control:
                - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
                - { path: ^/resetting, roles: IS_AUTHENTICATED_ANONYMOUSLY }
                - { path: ^/register/confirmed, roles: ROLE_USER }
                - { path: ^/register, roles: ROLE_ADMIN }
                - { path: ^/news, roles: ROLE_COMMUNICATION }
                - { path: ^/models, roles: ROLE_COMMUNICATION }
                - { path: ^/sliders, roles: ROLE_COMMUNICATION }
                - { path: ^/reviews, roles: ROLE_COMMUNICATION }
                - { path: ^/agencies, roles: ROLE_COMMERCIAL }
                - { path: ^/sectors, roles: ROLE_COMMERCIAL }
                - { path: ^/departments, roles: ROLE_COMMERCIAL }
                - { path: ^/, roles: ROLE_USER }